package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLabel(java.lang.String label) {
		set("label", label);
	}

	public java.lang.String getLabel() {
		return get("label");
	}

	public void setEditUser(java.lang.String editUser) {
		set("edit_user", editUser);
	}

	public java.lang.String getEditUser() {
		return get("edit_user");
	}

	public void setImgSrc(java.lang.String imgSrc) {
		set("img_src", imgSrc);
	}

	public java.lang.String getImgSrc() {
		return get("img_src");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setThumb(java.lang.Integer thumb) {
		set("thumb", thumb);
	}

	public java.lang.Integer getThumb() {
		return get("thumb");
	}

}
