package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setImgSrc(java.lang.String imgSrc) {
		set("img_src", imgSrc);
	}

	public java.lang.String getImgSrc() {
		return get("img_src");
	}

	public void setFollowNum(java.lang.Integer followNum) {
		set("follow_num", followNum);
	}

	public java.lang.Integer getFollowNum() {
		return get("follow_num");
	}

	public void setFansNum(java.lang.Integer fansNum) {
		set("fans_num", fansNum);
	}

	public java.lang.Integer getFansNum() {
		return get("fans_num");
	}

}
